<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Confluent.Kafka" Version="2.14.0" />
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
		<PackageReference Include="MongoDB.Driver" Version="3.1.0" />
	</ItemGroup>

	<!-- Configuración de empaquetado para docker -->
	<PropertyGroup>
		<RootNamespace>Isra.Demos.Microservicios.CuentaMovimientos</RootNamespace>
		<ContainerRepository>pesimx87/isra-microservicios-cuenta-movimientos</ContainerRepository>
		<ContainerImageTag>1.1.7</ContainerImageTag>
		<ContainerRegistry>docker.io</ContainerRegistry>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
		<ContainerPort>8070</ContainerPort>
	</PropertyGroup>

	<ItemGroup>
		<ContainerEnvironmentVariable Include="ASPNETCORE_ENVIRONMENT" Value="Development" />

		<!-- Añadir Labels (Metadatos de la imagen) -->
		<ContainerLabel Include="maintainer" Value="isra.saucedo50@outlook.com" />
	</ItemGroup>

</Project>
