<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-Isra.Demos.Microservicios.Saldo-3942afa1-2b53-4f81-8c9f-18695fad4e25</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Confluent.Kafka" Version="2.14.0" />
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
		<PackageReference Include="Npgsql" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Isra.Demos.Microservicios.Modelo\Isra.Demos.Microservicios.Modelo.csproj" />
	</ItemGroup>

	<!-- Configuración de empaquetado para docker -->
	<PropertyGroup>
		<RootNamespace>Isra.Demos.Microservicios.Saldo</RootNamespace>
		<ContainerRepository>pesimx87/isra-microservicios-saldo</ContainerRepository>
		<ContainerImageTag>1.1.0</ContainerImageTag>
		<ContainerRegistry>docker.io</ContainerRegistry>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0-alpine</ContainerBaseImage>
		<ContainerPort>8072</ContainerPort>
	</PropertyGroup>

	<ItemGroup>
		<ContainerEnvironmentVariable Include="ASPNETCORE_ENVIRONMENT" Value="Development" />

		<!-- Añadir Labels (Metadatos de la imagen) -->
		<ContainerLabel Include="maintainer" Value="isra.saucedo50@outlook.com" />
	</ItemGroup>
</Project>
