<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-Isra.Demos.Microservicios.EstadoCuenta-9dc606f7-a9ba-47eb-b1aa-30a3997e8223</UserSecretsId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Confluent.Kafka" Version="2.14.0" />
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Isra.Demos.Microservicios.Modelo\Isra.Demos.Microservicios.Modelo.csproj" />
	</ItemGroup>

	<!-- Configuración de empaquetado para docker -->
	<PropertyGroup>
		<RootNamespace>Isra.Demos.Microservicios.EstadoCuenta</RootNamespace>
		<ContainerRepository>pesimx87/isra-microservicios-estado-cuenta</ContainerRepository>
		<ContainerImageTag>1.1.0</ContainerImageTag>
		<ContainerRegistry>docker.io</ContainerRegistry>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0-alpine</ContainerBaseImage>
		<ContainerPort>8073</ContainerPort>
	</PropertyGroup>

	<ItemGroup>
		<ContainerEnvironmentVariable Include="ASPNETCORE_ENVIRONMENT" Value="Development" />

		<!-- Añadir Labels (Metadatos de la imagen) -->
		<ContainerLabel Include="maintainer" Value="isra.saucedo50@outlook.com" />
	</ItemGroup>
</Project>
