<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
		<PackageReference Include="Npgsql" Version="10.0.2" />
		<PackageReference Include="QuestPDF" Version="2026.5.0" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Isra.Demos.Microservicios.Modelo\Isra.Demos.Microservicios.Modelo.csproj" />
	</ItemGroup>

	<!-- Configuración de empaquetado para docker -->
	<PropertyGroup>
		<RootNamespace>Isra.Demos.Microservicios.WebApi</RootNamespace>
		<ContainerRepository>pesimx87/isra-microservicios-web-api</ContainerRepository>
		<ContainerImageTag>1.1.5</ContainerImageTag>
		<ContainerRegistry>docker.io</ContainerRegistry>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
		<ContainerPort>8074</ContainerPort>
	</PropertyGroup>

	<ItemGroup>
		<ContainerEnvironmentVariable Include="ASPNETCORE_ENVIRONMENT" Value="Development" />

		<!-- Añadir Labels (Metadatos de la imagen) -->
		<ContainerLabel Include="maintainer" Value="isra.saucedo50@outlook.com" />
	</ItemGroup>

</Project>
